AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ServerlessGOT-Knights-API

  Sample SAM Template for ServerlessGOT-Knights-API

Globals:
  Function:
    Timeout: 3

Resources:
  KnightsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GOTKnights
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  GetKnightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: got_knights/
      Handler: app.get_knights
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KnightsTable
      Events:
        GetKnights:
          Type: Api
          Properties:
            Path: /knights
            Method: get

Outputs:
  GetKnightsAPI:
    Description: "API Gateway endpoint URL for Prod stage for Get Knights function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/knights/"
  GetKnightsFunction:
    Description: "Get Knights Lambda Function ARN"
    Value: !GetAtt GetKnightsFunction.Arn
  GetKnightsFunctionIamRole:
    Description: "Implicit IAM Role created for Get Knights function"
    Value: !GetAtt GetKnightsFunctionRole.Arn
  KnightsTableName:
    Description: "Name of the DynamoDB table for knights"
    Value: !Ref KnightsTable
